name: flutter_solidart
description: A simple State Management solution for Flutter applications inspired by SolidJS
version: 0.1.0
repository: https://github.com/nank1ro/flutter_solidart

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  meta: ^1.8.0
  solidart:
    path: ../solidart

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^3.1.0

flutter:
